# Ref From: https://evine.win/p/%E6%88%91%E7%9A%84%E5%AE%B6%E5%BA%AD%E7%BD%91%E7%BB%9C%E8%AE%BE%E8%AE%A1%E6%80%9D%E8%B7%AF%E5%BC%80%E5%90%AFdebian%E7%9A%84%E6%97%81%E8%B7%AF%E7%94%B1%E4%B9%8B%E8%B7%AF%E4%B8%83/
---
port: 7890
socks-port: 7891
mixed-port: 7893
tproxy-port: 7895
routing-mark: 666
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: false
find-process-mode: 'off'
external-controller: 0.0.0.0:9090
secret: You_Secret
external-ui: ui
external-ui-name: xd
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
unified-delay: true
tcp-concurrent: true
authentication:
  - "Evine:ABCDEFGHIJK"
experimental:
  sniff-tls-sni: true
geodata-mode: true
geodata-loader: standard
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
profile:
  tracing: true
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true                     # 嗅探器开关，开启后对 redir-host 类型识别的流量进行强制嗅探，包含Tun、Redir和TProxy或DNS为redir-host
  # force-dns-mapping: false
  parse-pure-ip: true              # 对所有未获取到域名的流量进行强制嗅探
  override-destination: true       # 是否使用嗅探结果作为实际访问,默认 true，全局配置,优先级低于 sniffer.sniff 实际配置
  # sniff: # TLS 默认如果不配置 ports 默认嗅探 443
  #   TLS:
  #     ports: [443, 8443]
  #   HTTP: # 需要嗅探的端口, 默认嗅探 80
  #     ports: [80, 8080-8880]
  #     override-destination: true # 可覆盖 sniffer.override-destination
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:7874
  use-hosts: true
  enhanced-mode: redir-host
  default-nameserver:
    - 101.226.4.6
    - 114.114.114.114
    - 223.5.5.5
  nameserver:
    - "https://dns.alidns.com/dns-query"
    - "https://doh.pub/dns-query"
    - "https://doh.360.cn/dns-query"
  nameserver-policy:
    geosite:cn:
      - "https://dns.alidns.com/dns-query"
      - "https://doh.pub/dns-query"
      - "https://doh.360.cn/dns-query"
    geosite:geolocation-!cn:
      - "https://1.1.1.1/dns-query"
      - "https://8.8.8.8/dns-query"
  fallback:
    - 'https://1.1.1.1/dns-query'
    - 'https://8.8.8.8/dns-query'
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
  fake-ip-filter:
    - "+.*"
